# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    session:
        cookie_lifetime: 1800
        gc_maxlifetime: 1800
        cookie_secure: auto
        cookie_samesite: lax

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
