services:
    php:
        image: php:8.4-fpm
        container_name: quapio-php
        volumes:
            - .:/var/www/html
            - ./sessions:/var/lib/php/sessions
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            APP_ENV: prod
            PHP_SESSION_SAVE_PATH: /var/lib/php/sessions
        working_dir: /var/www/html
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        container_name: quapio-nginx
        ports:
            - "127.0.0.1:8010:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        restart: unless-stopped
